@startuml

actor "User" as user

package "Funktionale Einheit" {
    component [INTERLIS-Modellablage] as Modellablage
    component [interlis-repository-creator\n(Gradle-Plugin)] as Creator 
}

component [GRETL] as Gretl #f2f2f2

user --> Modellablage

Modellablage -- Gretl : use
Modellablage -- Creator : depends on

@enduml
